### ISSUE TITLE
Comparar diferentes frameworks de testing para Javascript

### ISSUE THREAD

**Issue by gonrial** [scvsoft/til#10]
Mocha y Chai son dos librerías completas que se usan para poder hacer testing unitario y permiten poder hacer otros tipos de testing también (por ejemplo usando chai-http)
También existen Jest, Enzyme e incluso Postman que permite hacer testing automático de APIs usando Newman.
La idea sería revisar mis preconceptos sobre estas herramientas y encontrar cuáles son las ventajas y desventajas de usar una u otra, o cuál sería la más rápida para implementar según el proyecto.

**Comment by morhook** [comment]
Muy buenas las slides @gonrial ! Que lástima que me lo perdí, parecía bien enfocado el tema
