### ISSUE TITLE
Aprendiendo a hacer subtítulos

### ISSUE THREAD

**Issue by agustinmulet** [scvsoft/til#100]
Siempre quisiste arreglar esos subtítulos desincronizados? O te hacía mal leer esos errores de ortografía que tienen algunos subs? No? Soy el único? 😢 
Siempre quisiste ser parte de un fansub de anime?

Si la respuesta es sí, entonces esta charla es para vos!

Vamos a ver distintas cosas como:
- Tipos de contenedores para videos
- Tipos de códecs (sí, es aburrido pero sirve ver un pantallazo)
- Tipos de subtítulos
- Roles durante la creación de un subtítulo
- Programas a utilizar
- Demo time!
En la demo vamos a ver:
- Crear un sub desde cero
- Extraer un subtítulo existente de un video si ya tiene (y cómo hacer si está quemado directo sobre el video!)
- Ponerle estilos a nuestro sub

Prometo que lo que vamos a ver de teoría va a ser corto, además yo tampoco sé muy en profundidad sobre lo que pienso hablar 🤣

**Comment by pfmmfp** [comment]
https://scvsoft.zoom.us/rec/share/gzIuaF4cUmLn1t3mTKZVFxSQYaQK_7lRWhIQlhwRTLIHVn3CFRBeuNy2u0Ns7QFP.gGH1qC_THM4eTItB 

Passcode: 1y$g0YBC
