### ISSUE TITLE
OpenAI, GPT y Dall-E.

### ISSUE THREAD

**Issue by fpfaffendorf** [scvsoft/til#101]
Con la impunidad de quien no tiene nada que perder y nunca ocupó cargos públicos es que les vengo a ofrecer esta TIL con sabor a master class sobre OpenAI.

- Qué es OpenAI ?
- Creación de una cuenta, pagos desde Argentina y Keys.
- Tokens y costos de los distintos modelos.
- Diferencia entre training, fine tunning y embedding 
- Ejemplos de prompts de classification, sumarize, expand y extract.
- Modelos y roles
- Playground de OpenAI para interactuar con los modelos sin programar.
- Optimización de prompts
- Request y responses usando curl y Python (con libs de openai, pandas y numpy) 
- Moderación de prompts
- Parametrización de prompts para controlar costos y creatividad de las respuestas.
- Fine tunning
- Embedding y context creation con "text-embedding-ada-002" 
- Entender el concepto de cosine similarity y producto vectorial
- Modelo "text-davinci-003"
- Breve ejemplo de Dall-E y prompt to image
- Breve explicación de Pinecone sin ejemplos concretos
- Lo que se viene de la mano de GPT-4

**Comment by fpfaffendorf** [comment]
Filminas de la parte 1: 
https://docs.google.com/presentation/d/1ol_ryd6JNBdbxoPxAVnocwoBkZIR6svKo9v7Y0E0uN4/edit?usp=sharing

**Comment by pfmmfp** [comment]
[Grabacion de la parte 1](https://scvsoft.zoom.us/rec/share/RE0esGU_wzZzNLy66VfJSkdSu7HI6DBUAHMGjCZFx1d_CgHPtdkbrf-ZTYp4rRUb.qCHJpLATQ8nQehaL) 

Passcode: #gSq0b1@

[Grabacion parte 2](https://scvsoft.zoom.us/rec/share/JYRnzS8eUhKGgEMqik3JCQbQeoaeGpp7DuBCgIHBty27pGokrSh6JlEEGnCYJF4Z.gVetUjDqwTKxEgRQ)

Passcode: f.43.f+F

**Comment by fpfaffendorf** [comment]
Filminas de la parte 2:
https://docs.google.com/presentation/d/1sKWWXKBJ1YyX7rhmhVJtoy_4ZhY9o-GpqFSiAc1gtkE/edit?usp=sharing

**Comment by fpfaffendorf** [comment]
Tarde pero no tardísimo dejo las filminas de la parte 3: https://docs.google.com/presentation/d/1j1mf61auZVcZd3Zn4aibfLivP6MEnstD7dl6Xy3dbzs/edit?usp=sharing
