### ISSUE TITLE
Fotografia 101 

### ISSUE THREAD

**Issue by paltasosa** [scvsoft/til#103]
Tenes una camara tirada por ahi y nunca la usas porque te intimida?

Te gusta sacar fotos con el celu y no logras que te queden tan cancheras como a tus amiguis?

En este espacio vamos a hacer una charla introductoria sobre la fotografia, conociendo sus conceptos basicos, viendo las posibilidades que brinda entender como se relacionan y descubriendo como usar tu camara o tu celu para disfrutar un poco mas de este hermoso arte.

Si se copan, despues seguimos avanzandolo mas todavia.

**Comment by pfmmfp** [comment]
https://scvsoft.zoom.us/rec/share/4WkL3nJkoT4jFWiCOpumQoITudeYEFCjR-GcAWcz15-NGCqg4LWkRdd3SudkLRMT.tqVtSU1kN1GyZtlg
Passcode: 9nI*J7EF
