### ISSUE TITLE
Repaso de citas de Byung-Chul Han sobre IA.

### ISSUE THREAD

**Issue by fpfaffendorf** [scvsoft/til#104]
> Nos enteramos de todo sin alcanzar un auténtico conocimiento. Las informaciones no conducen ni a la experiencia ni al conocimiento. Carecen de la negatividad de la transformación.
> El dolor es lo que distingue al pensar del calcular. Inteligencia significa «Escoger entre» (Inter-legere).
> **Byung-Chul Han**

Aquellos más propensos al pensamiento algorítmico y abstracto, los que invertimos infinitas horas de nuestras vidas conversando con máquinas, debemos ser quienes más se nutran de pensamientos sociales, filosóficos y espirituales a la hora de desarrollar herramientas de Inteligencia Artificial.

Debemos conservar en todo momento la duda respecto de estas tecnologías. Tener presentes los impactos y estar convencidos de que el destino al que nos llevan es el sitio que queremos para las generaciones futuras.

Nuestra historia demuestra que el progreso es imposible de detener. Pero debemos estar a la altura y pausar la marcha si fuese necesario. Volver a barajar y repartir las cartas nuevamente, las veces que sea necesario.

En esta TIL repasaremos citas del filósofo y pensador Byung-Chul Han. Indagaremos en su pesimismo respecto de estas tecnologías e intentaremos usarlas en nuestro favor con el objeto de encontrar un balance que nos permita avanzar con conciencia.

**Comment by morhook** [comment]
Hermosa charla! Hay grabación?
