### ISSUE TITLE
Prompt engineering concepts & techniques

### ISSUE THREAD

**Issue by germoscv** [scvsoft/til#105]
The massive use of GPT chats has proven to be a game changer for many proffesionals and work environments. Experts on the field have been able to even create **a full "software development company" with a functioning product**, all by accurately working with **GPT chats**. 
It seems obvious that knowing _**how to properly prompt a GPT chat**_ will become an **essential skill** in the near future, but it gets difficult sometimes to get the GPT to give us the answers we **really** need

For this TIL talk we'll see a couple of basic concepts about *__how GPT chats work to understand Natural Language (Tokenization)__*, and some of the **limitations** that come with them. 
We will present _**Prompt Engineering**_ as a way to improve our results and get the most out of GPT models like ChatGPT, applying different methods according to the expected result.

**Comment by germoscv** [comment]
https://docs.google.com/presentation/d/1SvEWAdIJQ61AcWH-XNF4kM2jqryBR7u4uCFkVQoHGVM/edit#slide=id.p

**Comment by morhook** [comment]
Muy buena Germo! Gracias.
