### ISSUE TITLE
Pubsub and BigQuery Pubsub CGP Features

### ISSUE THREAD

**Issue by Jhoa-scv** [scvsoft/til#108]
La ides de la charla es continuar explicandoles el proceso de integracion de Receiving <Optoro> con GCP y como hicimos tal configuracion.

**Comment by Jhoa-scv** [comment]
Chicos les dejo un repo con ejemplos de como hicimos la configuracion de los topicos y funciones. [Repo Here](https://github.com/Jhoa-scv/pubsub-functions-terraform/tree/main)

**Comment by morhook** [comment]
Muchisimas gracias Jhoa por compartir!
