### ISSUE TITLE
Side effects en Redux con Observables

### ISSUE THREAD

**Issue by holden-caulfield** [scvsoft/til#12]
Hace poco con @gabrieldaraio tuvimos que hacer una demo en RN + Redux y elegimos hacer los side effects con Redux-Observable (redux-observable.js.org). La idea es mostrar lo que hicimos, que cosas nos gustaron, que cosas no tanto y si de lo que no nos gustó tanto como quedó si se podría hacer de otra manera

**Comment by emanuelandrada** [comment]
A mí lo poquito que vi de RN me gustó, pero no tengo idea del mundo js. Si se explica también qué es, cómo se usa y qué resuelve Redux estaría bueno. :)
