### ISSUE TITLE
I'm SAML

### ISSUE THREAD

**Issue by morhook** [scvsoft/til#15]
En nuestro proyecto necesitamos integrar un login (SSO) con el protocolo SAML. 

Qué es SAML? Para que sirve? Cuales son los modos que tiene? Qué es un IdP? Qué es un SP? Que tecnologías utiliza internamente el protocolo y/o utiliza algún mecanismo de seguridad? Se pueden crear usuarios automáticamente en el SP? 

Viendo que es la segunda compañía que lo utiliza (previamente Opower y ahora esto es para AlarmDotCom) y el estándard está bastante estable, creemos que puede ser útil para otros futuros proyectos.

**Comment by fa-rodrigouroz** [comment]
En FutureAdvisor tambien lo vamos a utilizar, pronto. Con lo cual estoy dispuesto a comprar votos...

**Comment by morhook** [comment]
Veo que no compraste muchos @fa-rodrigouroz

**Comment by morhook** [comment]
https://docs.google.com/a/scvsoft.com/presentation/d/1OiJ9DQYYk_ZMH3UTZuUIDH0OsMPsGgCGsRRHswHA2ew/edit?usp=sharing
Para los que no vinieron!

**Comment by morhook** [comment]
[I'm SAML.pptx](https://github.com/scvsoft/til/files/1307656/I.m.SAML.pptx)
Para los que no tienen google drive de scvsoft (pero supongo que todos tendrán!)
