### ISSUE TITLE
Git workflows: github, gitflow?

### ISSUE THREAD

**Issue by tepen** [scvsoft/til#16]
Hace rato que venimos usando algo similar a gitflow en los proyectos, pero esto a veces choca con el flujo de los PRs en github. Estaria bueno ver las diferentes estrategias y soluciones de otros proyectos.
Bonus: hay varios que todavia no estan comodos con el flujo de Git, estaria bueno usar una TIL para dar una mano con eso.

**Comment by gonrial** [comment]
Me sumo con una alternativa que estamos usando nosotros: monorepo y todo en master.
