### ISSUE TITLE
Redux: "El tío Facho"

### ISSUE THREAD

**Issue by javierfernandes** [scvsoft/til#20]
Primero nos dicen que **React es la papa**, porque es más simple, porque es funcionaloide, porque no te ata a detalles de arquitectura como inyección de depcia (angular), fácil de testear, es reactivo y se actualiza sólo, etc....etc. 
**Entonces usamos react.**

Enseguida nos dicen _"Ah no, pero nadie usa React 'solo'"_ Entonces aparece **redux**. Que también es simple/funcional, testeable, etc etc..

Y al principio **Redux es bueno** y todo es felicidad, o bueno, confusión, pero luego felicidad cuando uno lo entiende.
Pero al final, redux es como un matrimonio (?), es todo genial hasta que pasan los años y uno se aburre de la rutina (???).

Nos queda la sensación de que no está buena la cantidad de boilerplate que se requiere al usar Redux. Y de que usar redux "esconde" ciertos patrones de más alto nivel que entonces se tornan repetitivos.

La propuesta de esta charla es debatir si Redux
* es realmente necesario ?
* si es necesario, es realmente necesario usarlo directamente ?
* en qué problemáticas particulares se requiere redux ? No hay algo que abstraiga de redux ?

Todo eso y mucho más en el primer capítulo de las charlas Fachas de SCV (?)

**Comment by holden-caulfield** [comment]
Programada para las 11hs el Viernes 22
