### ISSUE TITLE
La Bajada de Linea

### ISSUE THREAD

**Issue by holden-caulfield** [scvsoft/til#21]
Un problema que suele pasar siempre a la hora de arrancar un proyecto, y mucho más en Javascript  y React en particular, es la toma de un montón de decisiones de carácter semi subjetivo: hay pros y contras, pero en determinado punto es una cuestión de gustos.

Algunos ejemplos para Javascript + React:
- Que librería de test uso?
- Que code style uso?
- Qué uso para buildear/deployar?
- Uso Redux o no uso Redux?
- Si uso Redux, que uso para los side effects?
- etc, etc, etc

En general estas decisiones generan ciclos de evaluación/discusión que consumen UNA BOCHA de tiempo, y aún cuando llegues a la configuración "óptima" (si tal cosa existe) difícilmente recuperes el tiempo perdido.

Hace poco arranque un proyecto personal que como no tienen ningún deadline me vengo pudiendo dar el "lujo" de perder ese tiempo. 

Mi intención es pasarle las decisiones que tomé para ese proyecto y por qué, con la intención de que tomen algunas o todas ellas y las usen de manera más axiomática (si les copa), ahorrándose discusiones al pedo.

Tb espero que en la charla surja algún que otro debate, ya que muchas de las decisiones son polémicas. Pero al menos los tendríamos una vez en esta charla y no todos por separado al arrancar cada proyecto

**Comment by morhook** [comment]
`ember` ? `la jihad` ?

**Comment by holden-caulfield** [comment]
@morhook la mayoría de las cosas que estaría mostrando son decisiones que aplican tb si usas ember o angular. Y las que no, son justamente las cosas que ya te vienen resueltas por ser frameworks más autocontenidos

**Comment by holden-caulfield** [comment]
https://github.com/holden-caulfield/empa-trainer El repo para que chusmeen
