### ISSUE TITLE
Intro a Docker

### ISSUE THREAD

**Issue by npasserini** [scvsoft/til#23]
Seguramente a muchos nos tocó usar docker, pero la mayoría de las veces tocamos de oído. El primer objetivo de esta charla es entender un poco más de los conceptos básicos para poder administrar contenedores e imágenes y poder descular más fácil los problemas más comunes.

El segundo objetivo es empezar a tener una base común como para poder discutir cuáles son las mejores formas de aprovechar docker, docker-compose y (tal vez) swarm.

Un posible plan para la charla pueden encontrar [`acá`](https://github.com/npasserini/docker-workshop). Incluye temas como
- Conceptos básicos: image, container, network, service
- Crear y administrar contenedores create, start, stop, kill, rm
- Definir imágenes, Dockerfile 
- Administrar imágenes: build, pull, push, rm, run
- Consultar el estado de contenedores e imágenes: ls, ps, inspect
- House keeping: prune
- Networking: create, connect, disconnect
- docker-compose: 
  - conceptos: services, networks, volumes
  - archivos de configuración, docker-compose.yml y sus amigos
  - comandos básicos
- swarm, si llegamos.

**Comment by holden-caulfield** [comment]
https://scvsoft.zoom.us/recording/play/_jMt1x2sO03U5e-uKMCvPNWVttGBUeAFM5mhUou2WnT8q3sIudHsxeYwKhIIs_Vw

**Comment by morhook** [comment]
:1st_place_medal:
