### ISSUE TITLE
MacGitver

### ISSUE THREAD

**Issue by pipetus** [scvsoft/til#26]
Con Richard _Diff_ Anderson

En Avi-on, particularmente en el proyecto del _Remote Access Bridge_ (RAB, para los amigos), me ha tocado tener que hacer magia casi negra para lograr builds particularmente complicados, debido a las distintas características que tenían que tener determinados releases de prueba (firmware) casi concurrentemente.

Un rejunte de descubrimientos de un git poco usual, que normalmente no aplica a proyectos web, pero que quizás saber que existen estas herramientas ayude a otra alma en pena.

**Comment by vmariano** [comment]
Sumo unas tools extra, que les puede ayudar en los flows de trabajo. 
https://github.com/tj/git-extras

**Comment by pipetus** [comment]
Las slides.
https://docs.google.com/a/scvsoft.com/presentation/d/1Y9TqZUVNNuM5UUlChstngKfzkfQIIOqxoYb33Ygukbk/edit?usp=sharing
