### ISSUE TITLE
JSON API - una api que no es graphql 

### ISSUE THREAD

**Issue by morhook** [scvsoft/til#27]
Hola a todos. En la ronda de charlas del ecosistema Ember, proponemos indagar en JSON API. Es un protocolo basado en REST y JSON para normar la comunicación con el server.  Para los que no quieren votar la charla pero prefieren mirarlo solos: http://jsonapi.org/

**Comment by holden-caulfield** [comment]
https://scvsoft.zoom.us/recording/play/dm71sp6e_7tqG1Z9Fud1vUUnnHPtF2st7ybsE4ocer_PkVifPxDtTABc6IwMNM7W

**Comment by morhook** [comment]
Fe de erratas: `snake_case` es distinto a `skeleton-case` o `kebab-case`. La que está en el SPEC de JSON API para URLs, para los tipos y para los atributos es `kebab-case`
