### ISSUE TITLE
ember-cli o el CRA de ember

### ISSUE THREAD

**Issue by pfmmfp** [scvsoft/til#28]
Una visita a la [linea de comando](https://ember-cli.com/) de `ember`.

A grandes rasgos, provee, entre otras varias, las virtudes de [CRA](https://github.com/facebookincubator/create-react-app) pero desde 1995 (fecha aproximada +- 20 años)!

Se dice pionero en el mundo de las CLIs para frameworks front-end. Lo vemos facturas de por medio y le sacamos el cuero.

**Comment by morhook** [comment]
Y webpack?

**Comment by pfmmfp** [comment]
`ember-cli` bundlea assets también, como webpack
