### ISSUE TITLE
Bitcoins, blockchain y anti corpo

### ISSUE THREAD

**Issue by morhook** [scvsoft/til#31]
Hola a todos! En esta charla vamos a ver sobre el blockchain, como ejecuta el algoritmo, como correrlo en nuestra máquina y que significa para el sistema capitalista este nuevo modelo

**Comment by Javier-Rotelli** [comment]
dato de color: https://powercompare.co.uk/bitcoin/

**Comment by gonrial** [comment]
http://goo.gl/slides/h7cdn6

**Comment by gonrial** [comment]
https://scvsoft.zoom.us/j/102338900

**Comment by morhook** [comment]
Para que vean las slides (con links en las notas del presentador)
https://docs.google.com/a/scvsoft.com/presentation/d/1M_eiYKavsXAlvn2h5bF8542EeSK9erbS3YQMYJw-KxA/edit?usp=sharing

**Comment by morhook** [comment]
la grabación por zoom
https://scvsoft.zoom.us/recording/play/F7pK5hRjJ6eKkD8R0f6P9yaz5IXAe7-71s8GmavR-5fzbqLj1T6vXY3zbrZL5bKT

**Comment by gonrial** [comment]
Otra visión sobre el protocolo y la motivación financiera http://blog.ycombinator.com/building-for-the-blockchain/
