### ISSUE TITLE
Crystal: Fast as C, Slick as Ruby

### ISSUE THREAD

**Issue by afilgueira** [scvsoft/til#35]
https://crystal-lang.org/ la está rompiendo. Lo están haciendo los pibes de manas (https://manas.tech) y esta bastante interesante. 

Puedo a) tratar de que alguno se de una vuelta un viernes y nos cuente un poco de que trata todo esto o b) meterme en tema y preparar algo. Si podemos ir con a) tengo que coordinar la fecha bien.

**Comment by vmariano** [comment]
En que quedo esto? :(

**Comment by afilgueira** [comment]
Quedó pendiente :(. El flaco está ahora en Sri Lanka #posta

**Comment by vmariano** [comment]
@afilgueira Que onda?

**Comment by vmariano** [comment]
Avisá si esto revive.
