### ISSUE TITLE
CSS mas avanzado según Cruz

### ISSUE THREAD

**Issue by morhook** [scvsoft/til#37]
Hola a todos! 

Seguramente me conozcan de otras charlas, como Ember para los principiantes y CSS 101.

En esta charla vamos a ver sobre `critical path rendering`, FOUC (Flash of Unstyled Content) y como optimizar páginas estáticas. 

Esta charla se está basando en una [guía de google de Critical Path Rendering](https://developers.google.com/web/fundamentals/performance/critical-rendering-path/
)

**Comment by vmariano** [comment]
@morhook Que onda esto, tenes algo preparado?

**Comment by morhook** [comment]
Puedo armar la presentación y la doy!

**Comment by fa-cruzfernandez** [comment]
https://drive.google.com/open?id=1gHU6ez5ecF6i-rT6VGXbv1mOzUmXiLSz-hxy8zJodQE
(archivos presentación)
y grabación zoom:
https://scvsoft.zoom.us/recording/share/bsetYdKBu7_IQAOv-DLw5pBgXL41hoiuP5XxEQ9V316wIumekTziMw?startTime=1559311918000
