### ISSUE TITLE
Chamuyando sobre AI

### ISSUE THREAD

**Issue by holden-caulfield** [scvsoft/til#42]
Conceptos tocados de oído más las (pocas) experiencias laborales donde lo pude aplicar y que me pagaran por ello.

**Comment by vmariano** [comment]
@holden-caulfield sigue vivo esto?

**Comment by vmariano** [comment]
@holden-caulfield vas a dar esta charla si o no?

**Comment by holden-caulfield** [comment]
Ejemplo practico de AG: https://www.youtube.com/watch?v=FKbarpAlBkw

Otro ejemplo genial de algoritmo genético: https://youtu.be/qv6UVOQ0F44

Este fue el paper que publicaron los de openIA hace unos días presentando GPT 3 https://arxiv.org/pdf/2005.14165.pdf

https://www.kaggle.com/

Y acá va un link a un "cheat sheet" de topologías de RN: https://towardsdatascience.com/the-mostly-complete-chart-of-neural-networks-explained-3fb6f2367464

**Comment by holden-caulfield** [comment]
https://drive.google.com/file/d/1Y_aPE9RJ7dhqRK0x58FKqBmuGcGJabRo/view?usp=sharing

**Comment by morhook** [comment]
Cierro el issue porque esta charla ya se dió!
