### ISSUE TITLE
Retropie: ¿como volver a tener 10 años?

### ISSUE THREAD

**Issue by fa-rodrigouroz** [scvsoft/til#45]
Retropie es una imagen de raspberry optimizada para tener emuladores de consolas. https://retropie.org.uk/

En esta ocasion te mostramos como instalarlo desde cero, como ponerle ROMs y configurar cosas basicas (controles, video, audio).

La demo termina jugando, asi que en los comentarios pueden poner que juegos les gustaria probar y los llevo.

Las consolas que soporta: https://github.com/RetroPie/RetroPie-Setup/wiki/Supported-Systems

**Comment by fa-marianososa** [comment]
Me parece una linda alternativa que mandes una lista de shopping, asi sabemos que necesitariamos en caso de configurarlo. Quizas para ese dia, o quizas para mas adelante. No? Si la traemos ese dia, ya nos llevamos los roms. WIN WIN.

**Comment by fa-rodrigouroz** [comment]
- Retropie 3
- Cable HDMI
- SD Card (class 10)
- Power adapter (5V, 2500mAh)
- Joysticks (yo uso USB, se pueden configurar si son bluetooth pero nunca lo hice). Ver: https://github.com/RetroPie/RetroPie-Setup/wiki (Section: Controllers)

**Importante**: asi como viene, se puede jugar bien emulando consolas viejas. Para poder jugar mas cosas, conviene ponerle unos heat sink y/o comprar un case que disipe bien el calor (https://www.ebay.com/itm/Flirc-Raspberry-Pi-Case-Gen2-New-Model/123052628022?epid=2288490789&hash=item1ca6821836:g:k0UAAOSw0gFawOYI)

**Comment by fa-marianososa** [comment]
https://articulo.mercadolibre.com.ar/MLA-712038775-rs-raspberry-pi-3-model-b-1gb-12ghz-wifi-bt-_JM

https://articulo.mercadolibre.com.ar/MLA-637135084-cable-hdmi-1-metro-v14-fullhd-3d-4k-ultrahd-dorado-_JM

https://articulo.mercadolibre.com.ar/MLA-661949543-tarjeta-memoria-micro-sd-hc-capacidad-16gb-clase-10-kingston-_JM

https://articulo.mercadolibre.com.ar/MLA-621544264-fuente-cargador-5v-2-amper-2000mah-220v-_JM

https://articulo.mercadolibre.com.ar/MLA-710340404-joystick-analogico-pc-usb-seisa-con-vibracion-dualshock-_JM

**Comment by holden-caulfield** [comment]
Hacemos una vaquita entre todos y armamos una para la empresa de una buena vez?

**Comment by FedeCugliandolo** [comment]
¿la podemos conectar al fichin que tenemos tirado en el playroom?

**Comment by angelraver** [comment]
hacer andar ese fichin tendría que ser el proyecto

**Comment by fa-marianososa** [comment]
Yo creo que vamos a armar una para cada uno. Pero sin dudas, con una
vaquita dejar una armada en la empresa me parece lo mas logico.

El mayor problema del fichin creo que era la tele. Pero si armamos la
consolita, y conseguimos un monitor, lo armamos en ese mueble creeria yo,
no?

**Comment by fa-rodrigouroz** [comment]
Ok, estamos a miercoles. Si quieren tener una raspberry para el viernes, yo les diria que nos pongamos en campaña hoy. Arriba de todo hay links de ML.

**Comment by fa-rodrigouroz** [comment]
Yo traigo la mia, con unos ROMs para probar, y dos joysticks.

**Comment by kadorrna** [comment]
https://articulo.mercadolibre.com.ar/MLA-637110720-raspberry-pi-3-uk-element14-kit-fuente-25a-gabinete-disipa-_JM
