### ISSUE TITLE
Solr: Como jugar a ser Google

### ISSUE THREAD

**Issue by fa-rodrigouroz** [scvsoft/til#46]
Hola, si tenes una fuente de datos muy grande y queres hacer busquedas muy copadas, Solr es tu amigo: http://lucene.apache.org/solr/

Si alguno propone una fuente de datos grande, mejor, sino busco una yo. Solr te permite hacer busquedas exactas, difusas, clusterizaciones, y mucho mas.

Hace unos años implemente un motor de busqueda de curriculums y me dio muy buenos resultados. Te puedo contar de esa experiencia.

**Comment by morhook** [comment]
Muy bueno Rod! Hace algunos años yo tuve el gusto de trabajar un poco con SolR! Espero no perderme esta charla, así desempolvo mis conocimientos de esto

**Comment by vmariano** [comment]
@fa-rodrigouroz Esto sigue en pie? ya estar por cumplir 1 año, hay que escolarizarla o cerrarla.

**Comment by vmariano** [comment]
Avisame si la vas a dar y reabrimos.
