### ISSUE TITLE
AWS Batch: Como poner a otro a trabajar por vos

### ISSUE THREAD

**Issue by fa-rodrigouroz** [scvsoft/til#47]
AWS implemento un nuevo servicio: Batch.

Para un cliente hicimos un prototipo. Tienen un proceso computacional muy intensivo y hoy no lo pueden paralelizar mucho porque esta muy acoplado a la aplicacion.

Te vamos a mostrar como hicimos un servicio que, con el concepto de ser una API asincronica, delega la resolucion de trabajos en AWS Batch. Vamos a ver S3, AWS Lambda y AWS Batch. 

Lo que corre el batch no es otra cosa que una imagen de docker que vamos a armar y subir al registry, y vamos a ver como configurar los ECS a nuestro gusto, y que caracteristicas tiene el Batch (colas, prioridades, etc).

**Comment by vmariano** [comment]
Se perdieron los datos de la charla :(
