### ISSUE TITLE
Hello rollup world

### ISSUE THREAD

**Issue by pfmmfp** [scvsoft/til#48]
Tengo un hello world 🌎hecho con [rollup](https://rollupjs.org/guide/en) que podria llevar para que lo miremos y abramos la charla sobre la existencia misma de este bundler.

Si surgen dudas, googleamos entre todos 🔍

**Comment by morhook** [comment]
Pregunta newbie: es `rollup` un reemplazo del amigo `webpack`??

**Comment by pfmmfp** [comment]
Si, es una alternativa a webpack, pero más orientado a bundlear librerias en vez de apps.

**Comment by pfmmfp** [comment]
Me sincero. Nunca voy a dar esto 👋
