### ISSUE TITLE
The Shell of your System

### ISSUE THREAD

**Issue by pipetus** [scvsoft/til#51]
En principio, el título podría suponer una anglización de un improperio rioplatense, pero no: la idea es hacer una charla de _Advanced BASH scripting_ y repasar, si da el tiempo, otros shelles.

Teniendo algunas features como punto de partida, el objetivo sería recopilar esas cosas que nos hacen decir «Mirá lo que podía hacer y no lo sabía...», o el menos sutil, «Si lo hubiera sabido antes, la concha de tu hermana», donde el título cobraría un sentido más cercano a la cotidianeidad.

**Comment by vmariano** [comment]
Me interesa como oyente y me interesa si puedo aportar.

**Comment by holden-caulfield** [comment]
https://devhints.io/bash

**Comment by pipetus** [comment]
https://docs.google.com/presentation/d/1NT4ddeGupslJw91f6zVNfeWweS5G4ej098XGMkwbpjA/edit?usp=sharing

**Comment by morhook** [comment]
Muchas gracias Pepe!
