### ISSUE TITLE
Somos los piratas

### ISSUE THREAD

**Issue by holden-caulfield** [scvsoft/til#52]
Me hice dos setups distintos para home media center en casa:

Uno con Plex - Sickrage - Couch Potato - Transmission

y mas recientemente el que tengo ahora con Plex - Sonarr - Radarr - Deluge

La idea de la charla es contar un poco como armarlos, pros y contras de cada uno y estaría buenisimo que otros tb compartieran sus experiencias, sino la charla va a ser un poco corta. Si alguien trae una máquina, podemos intentar hacer un setup en vivo a ver si llegamos a terminarlo

**Comment by fa-marianososa** [comment]
Tengo una maquina virgen dispuesta a ser el sujeto de prueba. Espero estar para la fecha de esta charla.

**Comment by holden-caulfield** [comment]
Herramientas que fueron mostradas en la charla:
- *Plex* (https://www.plex.tv/). Media center (otras altenativas: Kodi)
- *Sonnar* (https://sonarr.tv/). Manager de series (otras alternativas: SickRage, SickBeard)
- *Radarr* (https://radarr.video/) Manager de pelis (otras alternativas: couch potato)
- *Transmission* (https://transmissionbt.com/). Deluge o casi cualquier otro cliente de torrent tb anda. Una buena lista para revisar es los que ya tienen un connector provisto por sonnar/radarr
- *Sub-zero.* Un plugin HERMOSO de plex para bajar subtitulos... a mi gusto lo único que realmente me funcionó bien, tanto en cuanto a simpleza como calidad de los subtitulos encontrados: https://github.com/pannal/Sub-Zero.bundle
