### ISSUE TITLE
Fui a nerdear.la y te lo cuento.

### ISSUE THREAD

**Issue by vmariano** [scvsoft/til#56]
![alt text](https://ugc.kn3.net/i/origin/http://3.bp.blogspot.com/-7Qp76n7YePw/TpuCEl4Q7PI/AAAAAAAAABo/IigAwYGEObU/s640/Chelsea+Bienvenidos+a+mi+nuevo+post.bmp "Logo Title Text 1")

Fui jueves y viernes a nerdear.la donde se hablo de un moton de cosas. Te lo puedo resumir asi nomas, como para que tengas en mente que charla deberias mirar, o que slides deberias chusmear.

Si te queres entrear, dejame esos puntitos abajo.

**Comment by aguscruiz** [comment]
tiene mi arrivoto, buen señor

**Comment by vmariano** [comment]
https://docs.google.com/presentation/d/1po0Odg9xqAhK6DQq5_LK7jT-X571ZjIbcOymA9Yptuw
