### ISSUE TITLE
Knapsack, Backtracking y Programación dinámica

### ISSUE THREAD

**Issue by SCVFedericoLochbaum** [scvsoft/til#61]
Bueno, la idea es contar que es un problema de [optimización](https://en.wikipedia.org/wiki/Optimization_problem), presentar [el problema de la mochila](https://en.wikipedia.org/wiki/Knapsack_problem) y pensarlo entre todos. Presentar [Backtracking](https://en.wikipedia.org/wiki/Backtracking) y [Programación dinámica](https://en.wikipedia.org/wiki/Dynamic_programming) (con ejemplos de código). Entender cuando usar uno o el otro y finalmente hacer un ejercicio entre todos.

Bonus: Contar por arriba que es [Programación lineal](https://en.wikipedia.org/wiki/Linear_programming) ?

**Comment by vmariano** [comment]
Bueno, ya te doctoraste, que onda?
