### ISSUE TITLE
Un día cuando mi vida esté menos prendida fuego voy a proponer una charla de programación funcional

### ISSUE THREAD

**Issue by npasserini** [scvsoft/til#64]
Todos hablamos de programación funcional, todos buscamos sus ventajas, pero... ¿qué es exactamente la programación funcional? ¿por qué estaría buena o no? ¿qué tiene que pasar para que funcione?

En esta charla Nico les va a explicar por qué todo lo que hacen está mal.

**Comment by nscarcella** [comment]
Uh, sí me dejas me prendo

**Comment by morhook** [comment]
Esta charla sigue en pie señor @npasserini ? Estimo que no, pero no quiero cerrar este issue bruscamente
