### ISSUE TITLE
Como acelerar los PRS.

### ISSUE THREAD

**Issue by vmariano** [scvsoft/til#66]
La idea seria abrir una mesa de charla, y mostrar un par de ideas y trucos, para que no sea un dolor  cada vez que tenes que mirar Pull Requests/o enviar prs.

**Comment by p4bloch** [comment]
Cuáles son los principales pain points?

**Comment by vmariano** [comment]
>Cuáles son los principales pain points?

En una primera instancia supongo que el tiempo o añejamiento, pero la idea es que todos participen.

**Comment by vmariano** [comment]
Gracias por venir!

**Comment by morhook** [comment]
Pudieron guardar algún video o ejemplos para los que no pudimos ir por horarios?

**Comment by vmariano** [comment]
Acá dejamos una guia con los temas que se discutieron:

https://medium.com/@m_vicent/desde-que-git-se-convirti%C3%B3-en-el-standard-de-la-industria-para-versiones-c%C3%B3digo-github-tomo-la-c5e72ef78bc4

Enjoy.
