### ISSUE TITLE
Intro a kubernetes por Cruz (K8S para los amigos)

### ISSUE THREAD

**Issue by holden-caulfield** [scvsoft/til#67]
Veremos en esta reunión una breve introducción a Kubernetes (k8s para los ameos)

* microservicios vs monolito
* kubectl, que es? Que hace?
* minikube. Que es? Que hace?
* un deploy con kubectl CLI
* un deploy con kubectl YAML
* deployar app propia (ya dockerizada) a minikube
* si tenemos tiempo, que es un servicio en k8s?

**Comment by morhook** [comment]
Ahí diagramé un poco mejor lo que vamos a ver en esta charla. Espero sus votos!

**Comment by morhook** [comment]
La presentación que se viene si alguno tiene tiempo. https://docs.google.com/presentation/d/1TiPA1J5vaQ3Mexh1FU2_iqH2Tg57buKiSlWyhmUSQ7A/edit?usp=sharing

**Comment by morhook** [comment]
Cerrando! Vamos a hacer la siguiente charla. Kubernetes 102.

**Comment by morhook** [comment]
Gracias a todos por venir.

**Comment by morhook** [comment]
https://scvsoft.zoom.us/rec/share/x91cD-rz125Jbqfz82jcBrEIXcfAeaa8h3IZ8vVcyx0mokTJozuugI6WUIIPB93f Password: 8F?w@1&L

**Comment by morhook** [comment]
Renovando credenciales (zoom se negó a dejar entrar a un usuario)

https://scvsoft.zoom.us/rec/share/plPT34iF385R8KFrXYR3rYgGIGYzyECeqtfON16-1BPy4oYAJHihR2obi79MrFwE.nbEcFqbY1hkYykLz
Access Passcode: 8F?w@1&L

**Comment by morhook** [comment]
Estas charlas se perdieron! que lástima!

**Comment by morhook** [comment]
Esta charla se salvó!!! https://drive.google.com/file/d/1jLFGx6jlhDHjASm4p1RGEUqfeZp__JLk/view?usp=drivesdk
