### ISSUE TITLE
Chamuyando sobre ergonomia

### ISSUE THREAD

**Issue by vmariano** [scvsoft/til#70]
El otro dia nos dieron un ergonomics 101 en el cliente.

Lo puedo re-adaptar a formato charla, si logro 7 o más. 👍

**Comment by aguscruiz** [comment]
![image](https://user-images.githubusercontent.com/15734630/82484471-5b01fd00-9ab0-11ea-97ab-dccead03f760.png)

Solo conseguimos 6 👍, se cancela el hospital

**Comment by vmariano** [comment]
No necesitas conseguir todos los votos si tenes mas cuentas de github.
![imagen](https://user-images.githubusercontent.com/796960/82495645-c86a5980-9ac1-11ea-977f-886b9a9820d8.png)

**Comment by vmariano** [comment]
https://www.youtube.com/watch?v=85no-RVOEgc

**Comment by morhook** [comment]
Gran charla! Muchas gracias! Mi esposa se terminó poniendo un teclado y un mouse en su escritorio. Cuanto tiempo le llevará adaptarse? Ya van varios días y no siente mejoras aún.

**Comment by vmariano** [comment]
No entiendo la pregunta @morhook a que te referis? 
Le mejoran la postura de alguna forma? Cambia la posicion?

**Comment by morhook** [comment]
Le mejora la postura, pero en los primeros días sintió dolores distintos. Con el tiempo se fue adaptando y ya ahora prefiere usar el teclado y el mouse.
