### ISSUE TITLE
Showcase Brunerhouse/Beanie: cómo construimos un servicio y motor para crear la parte conversacional de juegos

### ISSUE THREAD

**Issue by javierfernandes** [scvsoft/til#74]
En el proyecto para el cliente BrunerHouse (ex CEO de TellTale) estamos construyendo una herramienta y un servicio para crear la parte conversacional de juegos de aventuras narrativas (onda elige tu propia aventura).

Por un lado un SaaS que llamamos "Studio" que permite a escritores, productores y otros profesionales crear una historia con diálogos y decisiones. Una especie de diseñador de un "workflow".
Por otro lado un motor en LUA que se embebe dentro de un juego "host" (Unreal, mobile, Alexa, etc) y que sabe ejecutar una historia interactuando con el host para que éste resuelva la UI y toda la parte gráfica (o de voz en el caso de Alexa).

Acá una lista de características que resultaron temas interesantes a resolver desde el lado técnico:

* **Arquitectura con estado distribuído sincronizado** para implementar real-time collaboration tipo Google docs.
* **Versionado de historias**: tenemos un esquema que permite hacer tags de las historias, y branchear versiones alternativas. Tipo "git" pero in-house y más limitado, implementado sobre el mismo modelo de la "arquitectura de estado distribuído". También con un history de cambios.
* **Undo/Redo**: de nuevo sobre el mismo modelo de estado. La dificultad principal contra un undo/redo tradicional se da por la colaboración en un ambiente multiusuario  y la necesidad de hacer "safe" las operaciones de undo/redo detectando conflictos (o mejor aún con un modelo conflict-free)
* **Integraciones con TTS provider**: tenemos text-to-speech, como forma de prototipado de las historias generando audio. Nos integramos con **Amazon Polly** y **Google Cloud Text To Speech**. Además de usar la Browser API para TTS.
* **Editor de Diálogos**: implementamos un rich-editor como una especie de DSL para escribir diálogos similares a scripts de películas, con elementos extras como notas para el actor/productor y "markups" que permiten disparar comportamientos del juego en ciertas partes del diálogo
* **DSL**:  hicimos un lenguaje para expresar las partes dinámicas (programar) de las historias. Mediante un parser e interprete tanto en JS como en LUA. A futuro un analizar estático y type checker
* **Authorisation**: implementamos un mecanismo "influenciado" por GitHub para manejo de proyectos con organizaciones,  teams, transferencia de proyectos, herencia de roles, invites, etc.
* **SPA long sessions & releases**: cómo resolver el mismatch entre SPA con usuarios loggeados por meses, y la necesidad de actualizarlos al sacar nuevos releases con continuous deployment  (el famoso "update automático")
* **Bridge JS/LUA**: cómo embebemos el motor LUA en el Studio (JS) mediante un bridge con proxies dinámicos que nos abstraen del modelo basado en "pila" del intérprete LUA.
* **Generación de Video**: para los juegos de tipo "video" (onda BanderSnatch) cómo generamos videos placeholders con audio para prototipar la historia.

Cuestiones aún más técnicas que podrían desprender otras charlas a futuro si interesa:

* **Cómo resolvimos el mismatch entre el engine OOP y React/Redux**: el engine es bien OOP, con estado mutable y encapsulando la lógica de mutación. React/Redux prefieren un esquema de estado funcional `state => action => state`. Cómo lo resolvimos ?
* **Lesson Learnt de Redux**: el Studio es un IDE, mucho comportamiento en el front. Mucho indexado de data y sstressing de redux. Eso nos llevó a aprender varias lecciones sobre todo de performance sobre redux
* **Tests declarativos**: una conclusión sobre cómo codear y mantener un suite de unos 5k tests y no morir en el intento.

**Comment by morhook** [comment]
Porque cerraste esta charla? ya se dió y me la perdí Javi?

**Comment by javierfernandes** [comment]
Si si, ya la dimos hace ya un tiempo
Creo que había un video (privado) que guardó JP. Digo privado porque este repo es público.

**Comment by morhook** [comment]
Genial. Mañana voy a ver si consigo ese link.

**Comment by morhook** [comment]
Acá encontré el link: https://scvsoft.slack.com/archives/C6D472J4F/p1600712928029600
