### ISSUE TITLE
Astro - Bring Your Own Framework

### ISSUE THREAD

**Issue by agustinmulet** [scvsoft/til#84]
La verdad no se me ocurre un título muy interesante para ponerle al issue.

Hace poco me crucé con [Astro](https://astro.build) y me pareció algo súper interesante. Usa la "Islands architecture" y tiene como finalidad mandar la menor cantidad de JS posible al frontend, además de ser una onda "Bring your own frontend" ya que soporta P/React, Vue y Svelte (SolidJS dentro de muy poco)
Como ellos mismos lo dicen, no es algo que no se haya hecho antes pero creen que les está saliendo mejor que a otros.

Voy a ir preparando slides y cuando tenga alguna fecha estimada que pueda llegar a tener todo listo, aviso :)

**Comment by pfmmfp** [comment]
[registro filmico aqui](https://scvsoft.zoom.us/rec/share/fIzic861mmyOsaldN2TWB7omRLxt4TnReI_-KlzGCGOvjDYkkAbclcpxxcY3P9ki.b9x2iJivSTbdRN_L?startTime=1656097964000)
