### ISSUE TITLE
AWS 101

### ISSUE THREAD

**Issue by blanchma** [scvsoft/til#85]
Brief journey over the main services offered by AWS: accounts, permissions, networking, computing, databases, containers and serverless.

**Comment by morhook** [comment]
Nice seeing round here! I think it makes sense in english now. I'll vote it!!!

**Comment by pfmmfp** [comment]
Gracias! Va el [video](https://scvsoft.zoom.us/rec/share/tawkyuI2fsiSAZrcfvjLXdWeU9w4YoOS_Pqd289pH__PWMifuI8e_4dIsrIwXy5V.UidsOyPMK-_jG6f0?startTime=1654283479000)
