### ISSUE TITLE
DevEx para todes. 

### ISSUE THREAD

**Issue by scvsoft-javierrotelli** [scvsoft/til#87]
a que nos referimos cuando hablamos de DevEx?
como hacemos para que nuestros proyectos no sean imposibles de configurar? 
que pasa cuando hay muchos devs tocando lo mismo?

**Comment by f-nyx** [comment]
Ejemplo practico de como crear un proyecto en Node y configurar:

* Framework de test
* Linter
* Git hooks
* CI con GH Actions
* Variables de entorno

**Comment by pfmmfp** [comment]
- [Video](https://drive.google.com/file/d/1BVb_7MSQkS9RDsZEB3LhjSEyZm-c7l0n/view)
- [Codigo y slides](https://github.com/scvsoft/til/tree/master/sandbox/devex)
