### ISSUE TITLE
Metodologías aplicadas al diseño de productos y servicios

### ISSUE THREAD

**Issue by annienar** [scvsoft/til#88]
¿Es scrum una metodología? 
¿Agile es una filosofía o metodología o solo una buzz word?
¿Cuál es la diferencia entre Design Thinking y diseño UX/UI?

Estas y más preguntas las aclararemos el viernes 13 de Mayo en un TIL-Talk donde conversaremos sobre metodologías y filosofías de trabajo aplicadas al diseño y sugerencias para trabajar en equipos multidisciplinarios :3 

Pueden mandar preguntas por slack o comentar ↓

**Comment by vmariano** [comment]
Sumaria mas cosas de vocabulario del lado de diseño , como design system y buenas practicas para comunicarse con designers

**Comment by annienar** [comment]
Design System es un tema en si mismo y es algo que podemos organizar otra TIL, porque involucra bastante más, pero lo de buenas prácticas lo vamos a estar charlando :D

**Comment by pfmmfp** [comment]
Gracias Ani! Aca va la grabacion,

https://scvsoft.zoom.us/rec/share/rgIf3qsrHG2hFyQXoqYm-lsztaey7oB0O2hnL1KE5RxJj13-yr7tjEh-qAVGw2k.3TPuLQWMOsdwiKQl?startTime=1652468607000
Passcode: r5T9+jtr
