### ISSUE TITLE
Introducción a Vue

### ISSUE THREAD

**Issue by pato-pitaluga-avi-on** [scvsoft/til#89]
- ¿Por qué usar Vue?
- "Hello world"
- Distintas maneras de hacer el setup
- Características principales
  - Text Interpolation
  - Conditional rendering
  - List rendering
  - Attributes dinámicos / props
  - Events / methods / v-model
  - Classes / Styles dinámicos
  - Funciones del lifecycle
- Arquitecturas de componentes
- Ejemplo real life usando todo
- Truquitos

**Comment by pfmmfp** [comment]
📽 [Grabacion](https://scvsoft.zoom.us/rec/share/Dh6VqWCMiQK9AwOHmXrYMJ3-oqQ97CunABpy2ys0ALWAPzrv8t_mPlKGd2baDvRT.-1EKwKKY14d7lrQw)
