### ISSUE TITLE
Como crear un editor de código custom con syntax highlight, linting y autocomplete usando CodeMirror 6

### ISSUE THREAD

**Issue by FedeLochbaum** [scvsoft/til#92]
### Overview

[CodeMirror](https://codemirror.net/) es un componente web que permite definir, mediante diferentes extensiones, un editor de código "custom", ya sea para un lenguaje de programación conocido como para un lenguaje propio.

#### Objetivos

En esta charla pretendo contar:

- Contar algo de parsers LR y LL (algo básico)
- Cómo definir un mini lenguaje de programación de dominio especifico (lenguaje de queries de gmail) usando [Lezer](https://lezer.codemirror.net/), el parser generator de CodeMirror
- Cómo customizar el parser generado (LR)
- Cómo crear una extensión de codeMirror a partir del parser generado (y contar sobre 
- Cómo funciona la arquitectura del editor de CodeMirror (sin entrar demasiado en detalle sobre el sistema de transacciones)
- Cómo se integra nuestro lenguaje al editor de código
- Cómo definir un tema basado en los nodos del actual AST (incremental parsing) para aplicar syntax highlighting
- Cómo extender el editor con un Linter, generando feedback con reglas de Linting propias
- Cómo extender el editor con un contextual Autocomplete basado en el actual AST
- Cómo se agregan más extensiones como keybinding, tooltip data, custom node rendering, etc.

####  A modo de ejemplo, dejo una muestra de nuestro editor de código custom para el lenguaje Beanie

![1](https://user-images.githubusercontent.com/16744248/175180097-04d9e643-3e9c-40de-a674-fb64f94b1f20.gif)

![2](https://user-images.githubusercontent.com/16744248/175180103-4f7cf7e6-b454-4323-b040-5019d82cf99d.gif)

![3](https://user-images.githubusercontent.com/16744248/175180295-1aad5251-acf8-428a-8dd4-45fcf0218a9d.gif)

#### Acá algunos links:
- https://www3.cs.stonybrook.edu/~cram/cse504/Spring16/Lectures/Spring15/lrparser-handout.pdf
- https://cs.gmu.edu/~white/CS540/Slides/Parsing/CS540-2-lecture4.pdf
- https://codemirror.net/examples/lang-package/
- https://codemirror.net/docs/guide/
- https://codemirror.net/docs/ref/
- https://lezer.codemirror.net/docs/guide/#writing-a-grammar
- https://codemirror.net/try/

**Nota**: quizás en un futuro (No tan lejano) de como para hacer algunas Tils sobre problemáticas más complejas de lenguajes de programación,

E.g: Diseño de `Tokenizers` y `Parsers`, `Type systems`, `Bytecode` y representaciones intermedias de código, `Interpretes`, `Compiladores`, `Optimizaciones de compilación`, etc.

Si esto interesa puedo preparar algo :)

##### También puedo preparar algo sobre lógica, matemática discreta o algoritmos :;).

**Comment by pfmmfp** [comment]
[Video de la charla](https://scvsoft.zoom.us/rec/share/nnOgX42rabYEvPNkLiC0t_ASzhddaEuJ9rdChMVEUGtNSbYBDDDEeBllD7QvnhjV.W3_8EvKTCqiEW8mJ?startTime=1656702473000)
