### ISSUE TITLE
Grafana y monitoreo

### ISSUE THREAD

**Issue by pela-scv** [scvsoft/til#93]
Hablaremos un poco de monitoreo y alertas concentrandonos en Grafana y su stack

**Comment by pfmmfp** [comment]
* [Video de la charla](https://scvsoft.zoom.us/rec/share/Vp7VP8KbR0mF9pS9N1i-nss6b0FCsGKkmQbnyemOXTqVnziX38bk6-66wgXTP22_.WdqRT9e84h9iTnhH?startTime=1659726421000)
* https://github.com/xaavito/grafana Este es el proyecto que tiene todo
* https://github.com/xaavito/grafana-node-app Esta es la aplicacion en node que es sujeta a las metricas

**Comment by morhook** [comment]
Muy buena la charla! Gracias por compartir el video también para los diferidos o que tenemos ocupado el viernes a esa hora.
