### ISSUE TITLE
#NoEstimates

### ISSUE THREAD

**Issue by vmariano** [scvsoft/til#94]
Cansado de estimar? 

Cansado de discutir si es un 3 o un 5, Existe otra forma! 

En otra forma de A donde nos metemos agile? (#57)  continuamos con ,no estimates. Qudate para el debate final.

**Comment by vmariano** [comment]
https://docs.google.com/presentation/d/114VWfAv_MXDBYHu_uuq_WobPybQT1Y_HSwqxD7YKFaY/edit?usp=sharing

**Comment by pfmmfp** [comment]
[Video de la charla](https://scvsoft.zoom.us/rec/share/-47ylZaEZOzg4Lza6VA79rsUyOZu4EjrVVhfqIYdTFP6O1RKsrfiWK_LOWPjBlVZ.tEEbsGdgcWvlFOOt)

**Comment by vmariano** [comment]
Relacionado con el no estimates, me encotnre este video: https://www.youtube.com/watch?v=m5A1Wg8hYGo que si bien no habla del tema tambien hace unos puntos interesantes a la hora de planificar.
