### ISSUE TITLE
Serverless Offline: Soluciones a problemas de desarrollo en Cloud. 

### ISSUE THREAD

**Issue by TinchoCostamagna** [scvsoft/til#96]
Durante el desarrollo de la aplicacion nos encontramos con un gran problema en la etapa de desarrollo: Nos demandaba mucho tiempo probar nuestro codigo, pues trabajamos tecnologia serverless y cada vez que queriamos probar un cambio, debiamos deployar una lamdba a AWS. 
Nuestra solucion fue utilizar un plugin llamado serverless-offline, el cual nos permite crear un entorno local para correr la app y de esa manera probar cambios mas facilmente. 
En la charla vamos a ver un poco como emulamos un ecosistema Cloud en nuestro entorno local utilizando: 
-Docker
-DynamoDB
-Lambda AWS (utilizando serverless-offline)
-SQS
-MockServer

**Comment by pfmmfp** [comment]
[Grabacion de la charla](https://scvsoft.zoom.us/rec/share/vsyeIG_7b8A9G8MCuWf8K29yTnATyEhyzYI3EQeysXqx1Q8xLFabhYIW-O30zkLw.9iPqKZOxAfBfaVbl)
