### ISSUE TITLE
Paralelismo y Concurrencia en Ruby, Parte 1

### ISSUE THREAD

**Issue by bossiernesto** [scvsoft/til#97]
Introduccion a los conceptos de Concurrencia y Paralelismo. Diferencias. Que modelos de concurrencia existen actualmente en Ruby. Limitaciones de MRI

**Comment by morhook** [comment]
muchísimas gracias por la charla @bossiernesto !! muy buena y completa

**Comment by bossiernesto** [comment]
Gracias!!

**Comment by pfmmfp** [comment]
https://scvsoft.zoom.us/rec/share/-RuBMkTYx6VArjh_QxaaUIfqI2qpBwGHoGb2Vey547GqhjfxI8yK_IjEMdkjAt-u.Hs8kuD5lPk7BPUg5
Passcode: b6byv&r&
