### ISSUE TITLE
Paralelismo y Concurrencia en Ruby, Parte 2

### ISSUE THREAD

**Issue by bossiernesto** [scvsoft/til#98]
Mecanismos de concurrencia alternativos en Ruby. Fibers y Ractors

**Comment by pfmmfp** [comment]
[grabacion aqui](https://scvsoft.zoom.us/rec/share/tVvaUJJLgZU91kKIOqT5L8IFimHIdBXTSYpwe8o2aecaWY-SG-sFSK-T9vS3cNKV.EfUNLaAqUFDlTVvJ)

**Comment by morhook** [comment]
Buenísima la grabación! Muchas gracias por las explicaciones offline también Chereal!
